#!/bin/bash
set -e -u -o pipefail

MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-""}
MYSQL_DATABASE=${MYSQL_DATABASE:-""}
MYSQL_USER=${MYSQL_USER:-""}
MYSQL_PASSWORD=${MYSQL_PASSWORD:-""}
MYSQL_BOOTSTRAP_SCRIPT=${MYSQL_BOOTSTRAP_SCRIPT:-""}
MYSQLD_ARGS=${MYSQLD_ARGS:-""}

tfile=`mktemp`
if [[ ! -f "$tfile" ]]; then
    return 1
fi

chown -R mysql:mysql /var/lib/mysql
if [[ ! -e /var/lib/mysql/.bootstrapped ]]; then
    mysql_install_db --user mysql > /dev/null

    cat << EOF > $tfile
USE mysql;
FLUSH PRIVILEGES;
GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;
UPDATE user SET password=PASSWORD("$MYSQL_ROOT_PASSWORD") WHERE user='root';
EOF

    if [[ $MYSQL_DATABASE != "" ]]; then
        echo "CREATE DATABASE IF NOT EXISTS \`$MYSQL_DATABASE\` CHARACTER SET utf8 COLLATE utf8_general_ci;" >> $tfile

        if [[ $MYSQL_USER != "" ]]; then
            echo "GRANT ALL ON \`$MYSQL_DATABASE\`.* to '$MYSQL_USER'@'%' IDENTIFIED BY '$MYSQL_PASSWORD';" >> $tfile
        fi
    fi

    /usr/sbin/mysqld --bootstrap --verbose=0 $MYSQLD_ARGS < $tfile
    rm -f $tfile

    if [[ -n $MYSQL_BOOTSTRAP_SCRIPT && -f $MYSQL_BOOTSTRAP_SCRIPT ]]; then
        cat $MYSQL_BOOTSTRAP_SCRIPT >> $tfile

        /usr/bin/mysqld_safe > /dev/null 2>&1 &

        RET=1
        while [[ RET -ne 0 ]]; do
            echo "=> Waiting for confirmation of MySQL service startup"
            sleep 5
            set +e
            mysql -uroot -p$MYSQL_ROOT_PASSWORD -e "status" > /dev/null 2>&1
            RET=$?
            set -e
        done

        mysql -uroot -p$MYSQL_ROOT_PASSWORD $MYSQL_DATABASE < $MYSQL_BOOTSTRAP_SCRIPT

        mysqladmin -uroot -p$MYSQL_ROOT_PASSWORD shutdown
        sleep 5
    fi
    touch /var/lib/mysql/.bootstrapped
fi

exec /usr/sbin/mysqld $MYSQLD_ARGS
